services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: docker-postgres-1
    environment:
      POSTGRES_USER: growth_halo
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: growth_halo_local
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.5.0
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "3001:3000"
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    working_dir: /usr/src/app
    env_file:
      - docker/.env
    environment:
      PORT: 5000
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ..:/usr/src/app:cached        # Mount source
      - /usr/src/app/node_modules     # Prevent host override
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    working_dir: /usr/src/app
    environment:
      PORT: 3000
      VITE_BACKEND_URL: http://localhost:5000
    volumes:
      - ..:/usr/src/app:cached
      - /usr/src/app/client/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  redisdata:
  grafanadata:
  pgdata:
  